api_platform:
    title: 'Vote 4 Lunch'
    description: 'API réalisé par Elnéris Dang pour Omnilog SAS</br>
                  Version 1.0.0 - Octobre 2019 </br>
                  Pour toutes questions : elneris.dang@omnilog.fr'
    version: '1.0.0'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    collection:
        pagination:
            enabled: false
